language: python
python:
  - "2.7"
install: pip install -r requirements.txt
script:
  - trial globaleaks
  - apt-get install git -y
  - mkdir -p /data/globaleaks
  - git clone https://github.com/globaleaks/GlobaLeaks /data/globaleaks/GlobaLeaks
  - /data/globaleaks/GlobaLeaks/scripts/build-testing-package.sh
