sudo: required
dist: trusty
language: python
python:
  - "2.7"
node_js:
  - "0.12"
env:
  global:
    - secure: Fd+dALSXhRgP44UaiED0xbJMHLxzON1Vcu6ufxDGgyl9NYepT0cfMGczLocfawc35ig++SyfytfpaPRhy3yG7WhNiBmpq+M1rec5MDKh/tFSKV/JOmLxbUIAxByIgTH39e+bY2El0h+vqiB12JiArahBzraYMYY+Xkty3Ysr+9o=
    - secure: clvOWlojaHQMHGhrN+sG+jOVLAsGJQFpzlUBv+8tKNy+Xbv/XPOQvnzqFTCdRlHSd39wnwIQTwOCWaCYhEECEyqgpaxYlYpSPsUOmk12aSxfjH5YGdwFqZvqhw1rkBpaEyoLh4PT0d1oLeCcJvb0jNuU4YbYOtq7DIRJDih/hPg=
  matrix:
    - GLTEST='unit'
    - GLTEST='build_and_install'
    - GLTEST='end2end-0'
    - GLTEST='end2end-1'
    - GLTEST='end2end-2'
    - GLTEST='end2end-3'
    - GLTEST='end2end-4'
    - GLTEST='end2end-5'
    - GLTEST='end2end-6'
    - GLTEST='end2end-7'
    - GLTEST='end2end-8'
    - GLTEST='end2end-9'
    - GLTEST='end2end-10'
    - GLTEST='end2end-11'
    - GLTEST='end2end-12'
    - GLTEST='end2end-13'
addons:
  sauce_connect: true
install:
    - true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - $TRAVIS_BUILD_DIR/scripts/travis.sh
