language: python
python:
  - "2.7"
install: pip install -r requirements.txt
script:
  - trial globaleaks
  - sudo -i bash -c 'apt-get install git -y'
  - sudo -i bash -c 'mkdir -p /data/globaleaks'
  - sudo -i bash -c 'chown travis:travis /data/globaleaks'
  - sudo -i bash -c 'git clone https://github.com/globaleaks/GlobaLeaks /data/globaleaks/GlobaLeaks'
  - /data/globaleaks/GlobaLeaks/scripts/build-testing-package.sh
  - sudo -i bash -c 'add-apt-repository "deb http://deb.torproject.org/torproject.org $(lsb_release -s -c) main"'
  - sudo -i bash -c 'gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x886DDD89'
  - sudo -i bash -c 'gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -'
  - sudo -i bash -c 'apt-get update'
  - sudo -i bash -c 'apt-get install tor tor-geoipdb torsocks curl'
  - sudo -i bash -c 'curl https://raw.github.com/globaleaks/GlobaLeaks/master/scripts/install-debian.sh | head -n 440 > install-debian.sh'
  - sudo -i bash -c 'chmod +x install-debian.sh'
  - sudo -i bash -c './install-debian.sh'
  - sudo -i bash -c 'mkdir -p /data/globaleaks/deb/'
  - sudo -i bash -c 'cp /data/globaleaks/GLBackend_tmp/glbackend_build/deb_dist/globaleaks*deb /data/globaleaks/deb/'
  - sudo -i bash -c 'cd /data/globaleaks/deb/ && dpkg-scanpackages . /dev/null | gzip -c -9 > /data/globaleaks/deb/Packages.gz'
  - sudo -i bash -c 'echo "deb file:///data/globaleaks/deb/ /" >> /etc/apt/sources.list'
  - sudo -i bash -c 'apt-get update'
  - sudo -i bash -c 'apt-get install globaleaks -y --force-yes'
  - sudo -i bash -c 'echo "VirtualAddrNetwork 10.23.47.0/10" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "AutomapHostsOnResolve 1" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "TransPort 9040" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "TransListenAddress 127.0.0.1" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "DNSPort 5353" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "DNSListenAddress 127.0.0.1" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "HiddenServiceDir /var/globaleaks/torhs/" >> /etc/tor/torrc'
  - sudo -i bash -c 'echo "HiddenServicePort 80 127.0.0.1:8082" >> /etc/tor/torrc'
  - sudo -i bash -c '/etc/init.d/tor restart'
  - sudo -i bash -c 'env > DUMP; cat DUMP'
  - sudo -i bash -c '/etc/init.d/globaleaks restart'
