contact_links:
  - name: Ask the GlobaLeaks comunity on the Comunity Forum
    url: https://github.com/globaleaks/globaleaks/discussions/new
    about: Ask and discuss questions with other community members on the Comunity Forum.

  - name: Chat with the GlobaLeaks comunity on the Comunity Chat
    url: https://comunity.globaleaks.org
    about: Chat with the other community members on the Comunity Chat.
